### ISSUE TITLE
autoloop

### ISSUE THREAD

**Issue by charlieman** [zc62/mpv-scripts#2]
In your autoloop.lua script, you can use `"set loop-file inf"` instead of 10000.

**Comment by zc62** [comment]
I had `inf` before, but #1 made me change the code to take into account the case that this script is used in combination with built-in auto-profiles.

Actually this script is pretty much useless. The same goal can be achieved by the general purpose [`auto-profiles.lua`](https://github.com/wiiaboo/mpv-scripts/blob/master/auto-profiles.lua)

**Comment by Qwerty-Space** [comment]
However auto-profiles.lua has messier configuration, is twice the size, and has a weird hack.

Having a script like yours is a lot nicer.

**Comment by zc62** [comment]
I thought `auto-profiles.lua` is a must-have.

**Comment by zc62** [comment]
Closing because #3 made it much nicer.
